### ISSUE TITLE
Undefined variable: http_response_header

### ISSUE THREAD

**Issue by mickadoo** [airbrake/phpbrake#29]
We're using phpbrake in a Symfony application. 

This error occurs only outside of the request scope. This is possible because we have registered a shutdown function which checks for errors and sends them to Airbrake. 

In general Symfony's default error handler will handle the errors (and return true thereby removing the error so `error_get_last` will return false. It seems there is some situation though where the Symfony handler is not able to handle the error. In this case the shutdown function tries to notify Airbrake but it fails with this message

> Undefined variable: http_response_header

**Comment by vmihailenco** [comment]
Released v0.0.12 with your fix.
