### ISSUE TITLE
Library version is not updated in tag v0.1.1

### ISSUE THREAD

**Issue by amirrf** [airbrake/phpbrake#40]
We are using v0.1.1 which is the latest and still receiving this reminder in emails: 

> This project is using an outdated version of phpbrake (0.0.5). It is recommended to upgrade to the latest version (0.1.1).

It is still set to 0.0.5 in tag v0.1.1:
https://github.com/airbrake/phpbrake/blob/v0.1.1/src/Notifier.php#L112

**Comment by vmihailenco** [comment]
Thanks for reminding - I've released v0.1.2.
