### ISSUE TITLE
Airbrake into a CakePHP 3.x server

### ISSUE THREAD

**Issue by mauriciovillalobos** [airbrake/phpbrake#43]
Hey All

While I was integrating Airbrake into a CakePHP 3.x server, I noticed that it completely takes over the default error handling that CakePHP provides.
I made a new error handler class to have both the ability to send errors to Airbrake, and also continue with the default error handling.

Here's a gist https://gist.github.com/mauriciovillalobos/01a97f9ee6179ad70b17d54f37cc5010

**Comment by vmihailenco** [comment]
@mauriciovillalobos thanks for sharing - it looks useful. Would you like to add it to the readme somewhere in the [integrations](https://github.com/airbrake/phpbrake#monolog-integration) section?

**Comment by mauriciovillalobos** [comment]
@vmihailenco here's the pull request https://github.com/airbrake/phpbrake/pull/44

**Comment by vmihailenco** [comment]
Thanks, closing this.
