### ISSUE TITLE
Request for a support branch

### ISSUE THREAD

**Issue by sfgeorge** [airbrake/phpbrake#53]
Hello,

Thank you to the maintainers of this project for a helpful tool!

I have a selfish and embarrassing request - In addition to `master`, would you consider opening a support branch for improvements to legacy versions of this project?

For the dinosaurs among us who are still on php 5.3 (sigh), we'd like to make an improvement for consideration, to build atop v0.0.7 - the last available version of phpbrake that supports php 5.3.  

We are making enhancements to phpbrake 0.0.7 and want to contribute back, in case they changes may benefit others.  If you'd be willing to open a "support/0.0.7.x" branch, we can target a PR to that for consideration.  If you feel that opening an additional support branch is not worth the overhead, no worries - we'll still rebase and propose our changes atop master so that other people can benefit.

Thanks for considering!

**Comment by sfgeorge** [comment]
Closing... happy to say we've convinced ourselves to upgrade :)

**Comment by vmihailenco** [comment]
:) I am afraid there is no much interest in PHP 5.3 support anyway, so while we can create the branch we are unlikely to contribute much to the work needed to be done.
