### ISSUE TITLE
Empty notification

### ISSUE THREAD

**Issue by str** [airbrake/phpbrake#62]
I'm trying to debug why I don't get any error messages in my production environment. This is a dump of the notification after running `\Airbrake\Instance::notify(new \Exception('TEST'));`

```
vendor/airbrake/phpbrake/src/Notifier.php +193

array(2) {
  ["headers"]=>
  NULL
  ["data"]=>
  bool(false)
}
```

**Comment by str** [comment]
OK, I found out. The hosting provider (mediatemple) had allow_url_fopen = false, so the `stream_context_create` function in `vendor/airbrake/phpbrake/src/Http/DefaultClient.php` returned false.

Should it show a different error instead of silently die?

**Comment by str** [comment]
Awesome! Thank you!

**Comment by vmihailenco** [comment]
Thank you for reporting!
