### ISSUE TITLE
Wordpress plugin

### ISSUE THREAD

**Issue by vmihailenco** [airbrake/phpbrake#83]

**Comment by phumpal** [comment]
Makes sense to add it here. Will we maintain backwards compatibility with our now outdated airbrake-wordpress until this is ready?

https://github.com/airbrake/airbrake-wordpress

**Comment by vmihailenco** [comment]
I don't have such plans.

**Comment by vmihailenco** [comment]
@anmic it looks like you need to update https://github.com/airbrake/airbrake-wordpress/blob/master/airbrake-wordpress.php#L33-L47 and try to install plugin in Wordpress.
