### ISSUE TITLE
Class 'Airbrake\Errors\Warning' not found

### ISSUE THREAD

**Issue by VinceG** [airbrake/phpbrake#84]
We started receiving this errors quite frequently, we been using Airbrake for couple of years and this just started. Any idea what this might be?

```
SoapFault exception: [Client] Class 'Airbrake\Errors\Warning' not found in /var/www/avn.com/shared/vendor/airbrake/phpbrake/src/ErrorHandler.php:36
```

**Comment by vmihailenco** [comment]
That file did not change for 3 years - https://github.com/airbrake/phpbrake/blob/master/src/Errors/Warning.php. And there were no releases recently. I think it is something on your side.

**Comment by VinceG** [comment]
Thank You.
