### ISSUE TITLE
Support For Exception Chaining

### ISSUE THREAD

**Issue by ls-sean-fraser** [airbrake/phpbrake#86]
Currently, if a chained exception is passed to Airbrake, only information about the top most exception is registered to airbrake.

For example:
```php
try {
    try {
        //...
    } catch (LowLevelException $e) {
       throw new DomainSpecificException($message, $code, $e);
    }
} catch (Exception $e) {
     $airbrake->notify($e);
}
```
only the message, code and stack trace of `DomainSpecificException` gets shown in the airbrake logs, while the information about the `LowLevelException` is discarded (which is honestly the most useful bit for tracking down the problem).

Is there any way for Airbrake to retain this information within the logs?

**Comment by vmihailenco** [comment]
`$e->getPrevious` can be used to get nested exception which should be added to the `$notice['errors']` array like this:

```
{
  "errors": [
    {top level exception},
    {nested exception},
  ]
}
```

**Comment by lsdsav** [comment]
@vmihailenco How would the nested exceptions be displayed by the UI in that case? Would they be treated as separate errors or linked somehow?

**Comment by vmihailenco** [comment]
I will be a single error - https://airbrake.io/blog/airbrake-feature/new-nested-exceptions

**Comment by lsdsav** [comment]
Great. Thank you, @vmihailenco

**Comment by vmihailenco** [comment]
Fixed by https://github.com/airbrake/phpbrake/pull/90
