### ISSUE TITLE
MonologHandler using its own debug backtrace, losing exception context

### ISSUE THREAD

**Issue by rootpd** [airbrake/phpbrake#87]
When the exception is being written via Monolog, the `$record` contains `context` parameter with the whole exception and the stack trace of the exception.

`MonologHandler` ignores this and uses its own stack trace causing all exceptions having stack trace pointing to `Monolog\Logger` - https://github.com/airbrake/phpbrake/blob/master/src/MonologHandler.php#L33.

If available, `MonologHandler` should try to read trace from `$record['context']['exception']->getTrace()`.

**Comment by anmic** [comment]
@rootpd, Are these changes that you were expecting?

**Comment by rootpd** [comment]
@anmic Yes, it seems like the very thing. :+1:
