### ISSUE TITLE
Latest versions not in packagist

### ISSUE THREAD

**Issue by ls-sean-fraser** [airbrake/phpbrake#92]
Hello,

[Packagist](https://packagist.org/packages/airbrake/phpbrake) only has releases of this library up to 0.6.0. We were hoping to take advantage of the nested exception handling offered in 0.6.1, but that is not available in the public package manager. I imagine this is just something that needs to be triggered in packagist to sync the available tags?

**Comment by phumpal** [comment]
@ls-sean-fraser I've initiated the sync. Please let us know if you can see releases > 0.6.0

**Comment by vmihailenco** [comment]
Seems to be fixed thanks to @phumpal

**Comment by ls-sean-fraser** [comment]
Thank you @phumpal, it works now
